=== Gleb-Stasuyk/l2start-server/core/dist/game/data/xsd/spawns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="AIData" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="aggroRange" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:boolean" name="disableRandomAnimation" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:boolean" name="disableRandomWalk" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeX" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeY" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeZ" minOccurs="0" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required" />
														<xs:attribute type="xs:int" name="y" use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="shape" use="optional" />
									<xs:attribute type="xs:short" name="minZ" use="required" />
									<xs:attribute type="xs:short" name="maxZ" use="required" />
									<xs:attribute type="xs:int" name="rad" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="banned_territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required" />
														<xs:attribute type="xs:int" name="y" use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="shape" use="optional" />
									<xs:attribute type="xs:short" name="minZ" use="required" />
									<xs:attribute type="xs:short" name="maxZ" use="required" />
									<xs:attribute type="xs:int" name="rad" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="id" type="xs:positiveInteger" use="required" />
											<xs:attribute name="x" type="xs:integer" use="optional" />
											<xs:attribute name="y" type="xs:integer" use="optional" />
											<xs:attribute name="z" type="xs:integer" use="optional" />
											<xs:attribute name="heading" type="xs:integer" use="optional" />
											<xs:attribute name="count" type="xs:positiveInteger" use="optional" />
											<xs:attribute name="respawnDelay" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="chaseRange" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="periodOfDay" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:token">
														<xs:enumeration value="day" />
														<xs:enumeration value="night" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" use="optional" />
						<xs:attribute type="xs:string" name="zone" use="optional" />
						<xs:attribute type="xs:string" name="zones" use="optional" />
						<xs:attribute name="selection" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:enumeration value="all" />
									<xs:enumeration value="random" />
									<xs:enumeration value="randomFill" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute type="xs:positiveInteger" name="maximumNpc" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Gleb-Stasuyk/l2start-server/core/dist/game/data/spawns/Others/23_17.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="23_17">
		<npc id="20956" x="107424" y="-894" z="-3132" heading="58336" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="107829" y="-2001" z="-3252" heading="55665" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="109591" y="-2053" z="-3453" heading="43651" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="109677" y="-3" z="-3610" heading="13159" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="110692" y="-1224" z="-4008" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="112353" y="-1172" z="-3908" heading="24036" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="113524" y="-5522" z="-3884" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="113524" y="-5166" z="-3884" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="114877" y="-367" z="-3615" heading="26346" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="114966" y="-8048" z="-3536" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="115738" y="-862" z="-3568" heading="56275" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="116529" y="-1337" z="-3637" heading="555" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="117556" y="-370" z="-3607" heading="23902" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="117984" y="-8164" z="-3664" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="118070" y="-10108" z="-3336" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="119084" y="-3540" z="-3892" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="119726" y="-1193" z="-3723" heading="1922" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="119750" y="-9600" z="-3484" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="120112" y="-4774" z="-4100" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="120616" y="-4952" z="-4100" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="121916" y="-5392" z="-3876" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20956" x="123020" y="-6468" z="-3832" heading="0" respawnDelay="37" /> <!-- Past Knight -->
		<npc id="20959" x="124862" y="-10414" z="-3908" heading="0" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="126163" y="-1353" z="-2376" heading="18529" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="126499" y="-7972" z="-3804" heading="24953" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="126711" y="-3499" z="-3013" heading="18124" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="127789" y="-5551" z="-3289" heading="6311" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="127914" y="-13326" z="-3852" heading="0" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="128015" y="-13504" z="-3852" heading="0" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="128440" y="-12456" z="-3792" heading="0" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="128839" y="-11180" z="-3772" heading="0" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="129041" y="-11536" z="-3772" heading="0" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20959" x="129734" y="-7742" z="-3872" heading="55835" respawnDelay="37" /> <!-- Dark Guard -->
		<npc id="20963" x="113423" y="-5344" z="-3884" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="114865" y="-7514" z="-3536" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="115167" y="-8048" z="-3536" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="117984" y="-7808" z="-3664" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="118070" y="-9752" z="-3336" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="119084" y="-3184" z="-3892" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="119548" y="-9244" z="-3484" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="119587" y="-3362" z="-3892" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="119851" y="-9066" z="-3484" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="120717" y="-4774" z="-4100" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="121815" y="-4858" z="-3876" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="122017" y="-5214" z="-3876" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="122617" y="-6112" z="-3832" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="123174" y="-5018" z="-3404" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="124560" y="-10592" z="-3908" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="125609" y="-2492" z="-2772" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="126355" y="-4239" z="-3211" heading="28063" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="127612" y="-13504" z="-3852" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="128203" y="-1678" z="-2178" heading="9310" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="128638" y="-11180" z="-3772" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="129041" y="-10824" z="-3772" heading="0" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="20963" x="130917" y="-6675" z="-3547" heading="1535" respawnDelay="37" /> <!-- Bloody Lord -->
		<npc id="31651" x="119472" y="-28688" z="-3776" heading="7000" respawnDelay="60" /> <!-- Tablet of Vision -->
	</spawn>
</list>

=== Gleb-Stasuyk/l2start-server/core/dist/game/data/spawns/Aden/TheForbiddenGateway.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn zone="aden06_2518_05">
		<territory minZ="-2776" maxZ="-2576">
			<node x="177724" y="5656" />
			<node x="178808" y="5660" />
			<node x="179312" y="6968" />
			<node x="179308" y="8836" />
			<node x="179056" y="9048" />
			<node x="177344" y="9044" />
			<node x="177356" y="6112" />
		</territory>
		<npc id="18001" count="2" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="1" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="2" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_06">
		<territory minZ="-2776" maxZ="-2576">
			<node x="180192" y="5712" />
			<node x="181252" y="5704" />
			<node x="181676" y="6208" />
			<node x="181632" y="9020" />
			<node x="179936" y="9036" />
			<node x="179692" y="8768" />
			<node x="179720" y="6960" />
		</territory>
		<npc id="20672" count="1" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_07">
		<territory minZ="-2768" maxZ="-2468">
			<node x="177408" y="9460" />
			<node x="179068" y="9460" />
			<node x="179316" y="9704" />
			<node x="179308" y="11776" />
			<node x="178648" y="12892" />
			<node x="177748" y="12888" />
			<node x="177360" y="12432" />
		</territory>
		<npc id="18001" count="2" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="2" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="1" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_08">
		<territory minZ="-2768" maxZ="-2468">
			<node x="179716" y="9752" />
			<node x="179940" y="9444" />
			<node x="181656" y="9448" />
			<node x="181664" y="12432" />
			<node x="181252" y="12896" />
			<node x="180240" y="12868" />
			<node x="179736" y="11756" />
		</territory>
		<npc id="20672" count="1" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_30">
		<territory minZ="-3784" maxZ="-3184">
			<node x="187216" y="17084" />
			<node x="188904" y="15960" />
			<node x="190400" y="16356" />
			<node x="191836" y="21036" />
			<node x="188032" y="19568" />
		</territory>
		<npc id="20672" count="4" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="5" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="5" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_31">
		<territory minZ="-3768" maxZ="-3468">
			<node x="187256" y="22280" />
			<node x="187724" y="21144" />
			<node x="191332" y="22760" />
			<node x="187724" y="24400" />
		</territory>
		<npc id="20672" count="4" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="3" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="4" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_32">
		<territory minZ="-3660" maxZ="-3260">
			<node x="183976" y="14016" />
			<node x="186328" y="14152" />
			<node x="187664" y="19764" />
			<node x="185116" y="19164" />
			<node x="184084" y="17544" />
		</territory>
		<npc id="18001" count="4" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="5" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="4" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_33">
		<territory minZ="-3764" maxZ="-3064">
			<node x="185652" y="21252" />
			<node x="186900" y="21204" />
			<node x="187104" y="25460" />
			<node x="184224" y="26016" />
			<node x="184388" y="23060" />
		</territory>
		<npc id="18001" count="3" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="5" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="4" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_34">
		<territory minZ="-3808" maxZ="-3008">
			<node x="181316" y="27036" />
			<node x="187656" y="25320" />
			<node x="188040" y="28996" />
			<node x="186684" y="30864" />
			<node x="181824" y="31088" />
		</territory>
		<npc id="18001" count="8" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="8" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="8" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_36">
		<territory minZ="-2848" maxZ="-2448">
			<node x="182952" y="9880" />
			<node x="185436" y="9756" />
			<node x="187700" y="11588" />
			<node x="186668" y="13256" />
			<node x="183100" y="13004" />
		</territory>
		<npc id="18001" count="4" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="5" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="5" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_37">
		<territory minZ="-2808" maxZ="-2408">
			<node x="185944" y="7792" />
			<node x="187400" y="6096" />
			<node x="189028" y="8556" />
			<node x="189152" y="11116" />
			<node x="186288" y="9964" />
		</territory>
		<npc id="20672" count="4" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="5" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="4" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_38">
		<territory minZ="-2796" maxZ="-2396">
			<node x="181572" y="4164" />
			<node x="184760" y="4872" />
			<node x="186044" y="6308" />
			<node x="184864" y="9172" />
			<node x="182684" y="9200" />
		</territory>
		<npc id="20672" count="5" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="5" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="5" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_45">
		<territory minZ="-3704" maxZ="-3304">
			<node x="189612" y="20392" />
			<node x="193644" y="22076" />
			<node x="193212" y="23236" />
			<node x="189120" y="21516" />
		</territory>
		<npc id="20672" count="2" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_46">
		<territory minZ="-3732" maxZ="-3532">
			<node x="188004" y="24516" />
			<node x="191724" y="22848" />
			<node x="193000" y="23412" />
			<node x="188156" y="25572" />
		</territory>
		<npc id="20672" count="2" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_47">
		<territory minZ="-3720" maxZ="-3520">
			<node x="190956" y="17436" />
			<node x="191992" y="16712" />
			<node x="193592" y="21832" />
			<node x="192348" y="21248" />
		</territory>
		<npc id="20672" count="2" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="oren01_qm2218_01">
		<territory minZ="-5348" maxZ="-5048">
			<node x="79892" y="15052" />
			<node x="82008" y="15024" />
			<node x="84252" y="20204" />
			<node x="82604" y="22312" />
			<node x="80436" y="20496" />
			<node x="79172" y="18188" />
		</territory>
		<npc id="27098" count="4" respawnDelay="180" /> <!-- Ghost Fire - Quest Monster -->
	</spawn>
	<spawn zone="oren01_qm2218_02">
		<territory minZ="-5396" maxZ="-5096">
			<node x="88572" y="15016" />
			<node x="91048" y="15508" />
			<node x="89376" y="20648" />
			<node x="86664" y="22120" />
			<node x="86512" y="20164" />
		</territory>
		<npc id="27098" count="4" respawnDelay="180" /> <!-- Ghost Fire - Quest Monster -->
	</spawn>
</list>
